name: BayMcSuicide
version: '1.0'
main: org.Konsheng.BayMcSuicide
api-version: '1.21'
authors: [ Konsheng ]
description: 允许玩家使用自杀命令
commands:
  kill:
    description: 玩家自杀
    permission: baymc.suicide.kill
  514:
    description: 玩家自杀
    permission: baymc.suicide.514
  suicide:
    description: 玩家自杀
    permission: baymc.suicide.suicide
  die:
    description: 玩家自杀
    permission: baymc.suicide.die
  zisha:
    description: 玩家自杀
    permission: baymc.suicide.zisha
